# Site settings
title: Edgardo Hames
email: ehames@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Computer scientist and software developer. Co-founder of Bitlogic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ehames.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edgardohames
github_username:  ehames

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 